In [1]:
class Circle(object):
  def __init__(self, radius, color):
    self.radius = radius;
    self.color = color;

  def add_radius(self, r):
    self.radius = self.radius + r

In [ ]:
CircleObj = Circle(12, 'red')

CircleObj.add_radius(3)
print(CircleObj.radius)

In [ ]:
dir(CircleObj)

In [2]:
import seaborn as sns
import pandas as pd

In [3]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.iloc[1, 0]

10.34

In [7]:
with open("Example3.txt","w") as file1:
  file1.write("This is line A\n")

In [4]:
import numpy as np

In [5]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

In [6]:
print(A)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [8]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [22]:
np.dot(np.array([1,1]), np.array([1,1]))

2

In [10]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])